name: build
on:
  release:
    types: [created]
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: microbit-foundation/npm-package-versioner-action@v1
      - run: npm publish
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
